name: dagster
channels:
  - conda-forge
  - esri
dependencies:
  - arcgis=2.1.0.3=py39_10
  - arcgispro=3.1
  - arcpy=3.1=py39_arcgispro_41759
  - arcpy-base=3.1=py39_41759
  - gdal=3.4.0=arcgispro_py39_17150
  - geopandas
  - h5py=3.7.0=arcgispro_py39_0
  - icc_rt=2019.0.5=arcgispro_0
  - intel-openmp=2020.0=arcgispro_166
  - ipykernel=6.16.0=py_1
  - ipython=7.34.0=pyhbfea036_1
  - numpy=1.20.1=py39_0
  - pandas=1.4.4
  - scipy=1.6.2=py39_0
  - libxml2=2.10.3=arcgispro_0
  - matplotlib=3.6.0=py39_arcgispro_3
  - matplotlib-base=3.6.0=py39_arcgispro_4
  - mkl=2020.0=arcgispro_167
  - netcdf4=1.6.1=py39_arcgispro_1
  - pip
  - python=3.9.18=1
  - scipy=1.6.2=py39_0
  - pip:
    - azure-identity
    - azure-storage-file-datalake
    - dagster
    - dagster-azure
    - dagster-graphql
    - dagster-postgres
    - dagster-webserver
    - paramiko
    - pdfquery
    - pycryptodome
    - pyodbc
    - sqlalchemy
    - sqlalchemy_utils
